// NexusAI — Individual Tool Page Renderer
import { getToolBySlug, getToolsByCategory, getCategoryById, CATEGORIES } from '../registry.js';
import { renderToolCard } from './home.js';
import { getToolUI } from '../tools/toolUI.js';

export function renderToolPage(slug) {
    const tool = getToolBySlug(slug);
    if (!tool) return `<div class="container" style="padding:6rem 0;text-align:center"><h1>Tool not found</h1><a href="#/" class="btn btn-primary">Go Home</a></div>`;
    
    const cat = getCategoryById(tool.category);
    const related = getToolsByCategory(tool.category).filter(t => t.slug !== slug).slice(0, 3);
    const toolUI = getToolUI(slug);

    return `
    <div class="tool-page">
        <div class="container container-tool">
            <div class="tool-hero">
                <div class="breadcrumb">
                    <a href="#/">Home</a><span class="separator">›</span>
                    <a href="#/category/${tool.category}">${cat?.name || tool.category}</a><span class="separator">›</span>
                    <span>${tool.name}</span>
                </div>
                <h1>${tool.icon} ${tool.name}</h1>
                <p class="tool-subtitle">${tool.desc}</p>
            </div>
            
            ${toolUI}

            ${renderToolInfo(tool)}
            ${renderFAQ(tool)}
            ${renderRelatedTools(related)}
        </div>
    </div>`;
}

function renderToolInfo(tool) {
    return `
    <div class="tool-info-section">
        <div class="section-header"><h2>Why Use Our <span class="text-gradient">${tool.name}</span>?</h2></div>
        <div class="tool-info-grid">
            <div class="tool-info-card">
                <h4>⚡ Instant Results</h4>
                <p>Get AI-powered results in seconds. No waiting, no queues. Our ${tool.name.toLowerCase()} processes your request instantly.</p>
            </div>
            <div class="tool-info-card">
                <h4>🎯 How to Use</h4>
                <ol>
                    <li>Enter your input in the text field above</li>
                    <li>Adjust any optional settings</li>
                    <li>Click "Generate" to get AI results</li>
                    <li>Copy or download your output</li>
                </ol>
            </div>
            <div class="tool-info-card">
                <h4>🔒 Privacy First</h4>
                <p>Your data stays private. We process everything locally when possible and never store your inputs or outputs.</p>
            </div>
        </div>
    </div>`;
}

function renderFAQ(tool) {
    const faqs = [
        { q: `Is the ${tool.name} really free?`, a: `Yes! Our ${tool.name.toLowerCase()} is 100% free to use with no hidden costs, no signup required, and no usage limits.` },
        { q: `How does the ${tool.name} work?`, a: `Our tool uses advanced AI algorithms to process your input and generate high-quality results. Simply enter your text or content, click generate, and get instant results.` },
        { q: `Can I use the results commercially?`, a: `Yes, all outputs generated by our ${tool.name.toLowerCase()} are free to use for any purpose, including commercial projects.` },
        { q: `Is my data safe?`, a: `Absolutely. We prioritize your privacy. Data is processed in your browser when possible, and we never store your inputs or outputs on our servers.` },
    ];
    return `
    <div class="faq-section">
        <h3>Frequently Asked <span class="text-gradient">Questions</span></h3>
        <div class="faq-list">
            ${faqs.map(f => `
            <div class="faq-item">
                <button class="faq-question">${f.q}<span class="faq-arrow">▼</span></button>
                <div class="faq-answer"><div class="faq-answer-content">${f.a}</div></div>
            </div>`).join('')}
        </div>
    </div>`;
}

function renderRelatedTools(tools) {
    if (!tools.length) return '';
    return `
    <div class="related-tools">
        <h3>Related <span class="text-gradient">Tools</span></h3>
        <div class="related-tools-grid">
            ${tools.map((t, i) => renderToolCard(t, i)).join('')}
        </div>
    </div>`;
}
